# .gitlab-ci.yml
pages: # 必須定義一個名為 pages 的 job
  image: node:latest
  stage: deploy
  script:
    - yarn install --frozen-lockfile
    - yarn build
    - mv public public-vue # GitLab Pages 的鉤子設定在 public 檔案夾
    - mv dist public # 重命名 dist 檔案夾 (npm run build 之後的輸出位置)
  artifacts:
    paths:
      - public # artifact path 一定要在 /public , 這樣 GitLab Pages 才能獲取
  only:
    - master